# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a778a8b7e9896e589f17e94fb8193d437e7a46dcfaf548f04720543022d71ba75629bb3a3536d36cb85d56829646d38e5c2c980c1fc83c36a498292c90a4335d

test:
  secret_key_base: fd08d22363054b01f605f8119eddbad09700a32370b63ffcad09b533eefdcf48f882e25183a7f1d1796e1ba657a774a2d06a8fb4634df8c9d71542857bbbf164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
